//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.ThongTinNhanViens = new HashSet<ThongTinNhanVien>();
        }
    
        public int IdNV { get; set; }
        public Nullable<int> IdTraSua { get; set; }
        public Nullable<int> IdTopping { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual MenuTopping MenuTopping { get; set; }
        public virtual MenuTraSua MenuTraSua { get; set; }
        public virtual ICollection<ThongTinNhanVien> ThongTinNhanViens { get; set; }
    }
}
