//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNSTS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinNhanVien
    {
        public int Id { get; set; }
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string Diachi { get; set; }
        public string SDT { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<int> ChucVu { get; set; }
    
        public virtual BangChamCong BangChamCong { get; set; }
        public virtual OrderDetail OrderDetail { get; set; }
        public virtual TaiKhoanNhanVien TaiKhoanNhanVien { get; set; }
    }
}
